/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp org.freedesktop.atspi.Registry.xml -c QSpiRegistryProxy -p registry-proxy
 *
 * dbusxml2cpp is Copyright (C) 2008 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef REGISTRY_PROXY_H
#define REGISTRY_PROXY_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>


struct QSpiAppUpdate {
    int     updateType;
    QString appPath;
};

Q_DECLARE_METATYPE (QSpiAppUpdate)

QDBusArgument &operator<< (QDBusArgument &args, const QSpiAppUpdate &in);
const QDBusArgument &operator>> (const QDBusArgument &args, QSpiAppUpdate &out);

/*
 * Proxy class for interface org.freedesktop.atspi.Registry
 */
class QSpiRegistryProxy: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.atspi.Registry"; }

public:
    QSpiRegistryProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

public Q_SLOTS: // METHODS
    inline QDBusReply<void> deregisterApplication(const QString &app)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(app);
        return callWithArgumentList(QDBus::Block, QLatin1String("deregisterApplication"), argumentList);
    }

    inline QDBusReply<QStringList> getApplications()
    {
        QList<QVariant> argumentList;
        return callWithArgumentList(QDBus::Block, QLatin1String("getApplications"), argumentList);
    }

    inline QDBusReply<void> registerApplication(const QString &app)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(app);
        return callWithArgumentList(QDBus::Block, QLatin1String("registerApplication"), argumentList);
    }

    inline QDBusReply<QSpiAppUpdate> updateApplications()
    {
        QList<QVariant> argumentList;
        return callWithArgumentList(QDBus::Block, QLatin1String("updateApplications"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void updateApplications (QSpiAppUpdate &update);
};

namespace org {
  namespace freedesktop {
    namespace atspi {
      typedef ::QSpiRegistryProxy Registry;
    }
  }
}
#endif
