/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -i adaptor_marshallers.h -c QSpiAccessibleAdaptor -a accessible_adaptor org.freedesktop.atspi.Accessible.xml
 *
 * dbusxml2cpp is Copyright (C) 2008 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ACCESSIBLE_ADAPTOR_H_1239785872
#define ACCESSIBLE_ADAPTOR_H_1239785872

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "adaptor_marshallers.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.freedesktop.atspi.Accessible
 */
class QSpiAccessibleAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.atspi.Accessible")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.atspi.Accessible\" >\n"
"    <property access=\"read\" type=\"s\" name=\"name\" />\n"
"    <property access=\"read\" type=\"s\" name=\"description\" />\n"
"    <property access=\"read\" type=\"o\" name=\"parent\" />\n"
"    <property access=\"read\" type=\"i\" name=\"childCount\" />\n"
"    <method name=\"getChildren\" >\n"
"      <arg direction=\"out\" type=\"ao\" />\n"
"    </method>\n"
"    <method name=\"getChildAtIndex\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"index\" />\n"
"      <arg direction=\"out\" type=\"o\" />\n"
"    </method>\n"
"    <method name=\"getIndexInParent\" >\n"
"      <arg direction=\"out\" type=\"i\" />\n"
"    </method>\n"
"    <method name=\"getRelationSet\" >\n"
"      <arg direction=\"out\" type=\"a(uao)\" />\n"
"      <annotation value=\"QSpiRelationArray\" name=\"com.trolltech.QtDBus.QtTypeName.Out0\" />\n"
"    </method>\n"
"    <method name=\"getRole\" >\n"
"      <arg direction=\"out\" type=\"u\" />\n"
"    </method>\n"
"    <method name=\"getRoleName\" >\n"
"      <arg direction=\"out\" type=\"s\" />\n"
"    </method>\n"
"    <method name=\"getLocalizedRoleName\" >\n"
"      <arg direction=\"out\" type=\"s\" />\n"
"    </method>\n"
"    <method name=\"getInterfaces\" >\n"
"      <arg direction=\"out\" type=\"as\" />\n"
"    </method>\n"
"    <method name=\"getState\" >\n"
"      <arg direction=\"out\" type=\"au\" />\n"
"      <annotation value=\"QSpiIntList\" name=\"com.trolltech.QtDBus.QtTypeName.Out0\" />\n"
"    </method>\n"
"    <method name=\"getAttributes\" >\n"
"      <arg direction=\"out\" type=\"as\" />\n"
"    </method>\n"
"    <method name=\"getApplication\" >\n"
"      <arg direction=\"out\" type=\"o\" />\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    QSpiAccessibleAdaptor(QObject *parent);
    virtual ~QSpiAccessibleAdaptor();

public: // PROPERTIES
    Q_PROPERTY(int childCount READ childCount)
    int childCount() const;

    Q_PROPERTY(QString description READ description)
    QString description() const;

    Q_PROPERTY(QString name READ name)
    QString name() const;

    Q_PROPERTY(QDBusObjectPath parent READ getParent)
    QDBusObjectPath getParent() const;

public Q_SLOTS: // METHODS
    QDBusObjectPath getApplication();
    QStringList getAttributes();
    QDBusObjectPath getChildAtIndex(int index);
    QList<QDBusObjectPath> getChildren();
    int getIndexInParent();
    QStringList getInterfaces();
    QString getLocalizedRoleName();
    QSpiRelationArray getRelationSet();
    uint getRole();
    QString getRoleName();
    QSpiIntList getState();
Q_SIGNALS: // SIGNALS
};

#endif
