/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -c QSpiAccessibleAdaptor -a accessible-adaptor org.freedesktop.atspi.Accessible.xml
 *
 * dbusxml2cpp is Copyright (C) 2008 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ACCESSIBLE-ADAPTOR_H_1237817910
#define ACCESSIBLE-ADAPTOR_H_1237817910

#include "adaptor_marshallers.h"
#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.freedesktop.atspi.Accessible
 */
class QSpiAccessibleAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.atspi.Accessible")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.atspi.Accessible\" >\n"
"    <tp:docstring xmlns=\"http://www.w3.org/1999/xhtml\" >\n"
"      <p>The base interface which is implemented by all accessible objects. \n"
"      All objects support interfaces for querying their contained 'children' \n"
"      and position in the accessible-object hierarchy, whether or not they\n"
"      actually have children.  </p>\n"
"      <p>Events that may be emitted by instances of Accessible include:\n"
"      \"object:property-change\" A base (strongly-typed) object attribute has changed,\n"
"      for instance \"object:property-change:accessible-name\".\n"
"      Notifed property subtypes include accessible-name, accessible-description,\n"
"      accessible-parent and accessible-role.</p>\n"
"      <p>\"object:children-changed\" The number or identity of an object's children\n"
"      has changed.\n"
"      \n"
"      \"object:state-changed\" The object's StateSet has had a state added\n"
"      or removed.\n"
"      \n"
"      \"object:active-descendant-changed\" If the object includes \n"
"      STATE_MANAGES_DESCENDANTS, this event is fired to indicate that the \n"
"      descendant having STATE_ACTIVE has changed; this corresponds to\n"
"      \"micro\" keyboard focus when the containing/emitting object has\n"
"      \"macro\" or technical keyboard focus.  For instance, this event is\n"
"      usually emitted while traversing tables and/or spreadsheet cells.\n"
"      \n"
"      \"object:attribute-change\" A weakly-typed property, as contained in the\n"
"      AttributeSet returned by Accessible::getAttributes, has changed in value,\n"
"      been added, or been removed from the object.\n"
"      (\"object:attribute-change\" notifications were added in AT-SPI 1.7.0)</p>\n"
"    </tp:docstring>\n"
"    <tp:property access=\"readwrite\" type=\"s\" name=\"name\" >\n"
"      <tp:docstring>\n"
"    A (short) string representing the object's name.\n"
"  </tp:docstring>\n"
"    </tp:property>\n"
"    <tp:property access=\"readwrite\" type=\"s\" name=\"description\" >\n"
"      <tp:docstring>\n"
"    A string describing the object in more detail than name.\n"
"  </tp:docstring>\n"
"    </tp:property>\n"
"    <tp:property access=\"read\" type=\"o\" name=\"parent\" >\n"
"      <tp:docstring>\n"
"    The Accessible object which is this object's containing object.\n"
"  </tp:docstring>\n"
"    </tp:property>\n"
"    <tp:property access=\"read\" type=\"i\" name=\"childCount\" >\n"
"      <tp:docstring>\n"
"    The number of children contained by this object.\n"
"  </tp:docstring>\n"
"    </tp:property>\n"
"    <method name=\"getChildren\" >\n"
"      <tp:docstring>\n"
"      Get the accessible children of this object.\n"
"    </tp:docstring>\n"
"      <arg direction=\"out\" tp:type=\"AccessibleSet\" type=\"ao\" >\n"
"        <tp:docstring>\n"
"      The Accessible children of this object.\n"
"    </tp:docstring>\n"
"      </arg>\n"
"    </method>\n"
"    <method name=\"getChildAtIndex\" >\n"
"      <tp:docstring>\n"
"      Get the accessible child of this object at index.\n"
"    </tp:docstring>\n"
"      <arg direction=\"in\" type=\"i\" name=\"index\" >\n"
"        <tp:docstring>\n"
"      an in parameter indicating which child is requested (zero-indexed).\n"
"    </tp:docstring>\n"
"      </arg>\n"
"      <arg direction=\"out\" tp:type=\"Accessible\" type=\"o\" >\n"
"        <tp:docstring>\n"
"      the 'nth' ::Accessible child of this object.\n"
"    </tp:docstring>\n"
"      </arg>\n"
"    </method>\n"
"    <method name=\"getIndexInParent\" >\n"
"      <tp:docstring>\n"
"      Get the index of this object in its parent's child list.\n"
"    </tp:docstring>\n"
"      <arg direction=\"out\" type=\"i\" >\n"
"        <tp:docstring>\n"
"      A long integer indicating this object's index in the parent's list.\n"
"    </tp:docstring>\n"
"      </arg>\n"
"    </method>\n"
"    <method name=\"getRelationSet\" >\n"
"      <tp:docstring>\n"
"      Get a set defining this object's relationship to other accessible objects.\n"
"    </tp:docstring>\n"
"      <arg direction=\"out\" tp:type=\"RelationSet\" type=\"a(uao)\" >\n"
"        <annotation value=\"QSpiRelationArray\" name=\"com.trolltech.QtDBus.QtTypeName.Out0\" />\n"
"        <tp:docstring>\n"
"      A RelationSet defining this object's relationships.\n"
"    </tp:docstring>\n"
"      </arg>\n"
"    </method>\n"
"    <method name=\"getRole\" >\n"
"      <tp:docstring xmlns=\"http://www.w3.org/1999/xhtml\" >\n"
"      Get the Role indicating the type of UI role played by this object.\n"
"    </tp:docstring>\n"
"      <arg direction=\"out\" tp:type=\"Role\" type=\"u\" >\n"
"        <tp:docstring>\n"
"      A Role indicating the type of UI role played by this object.\n"
"    </tp:docstring>\n"
"      </arg>\n"
"    </method>\n"
"    <method name=\"getRoleName\" >\n"
"      <tp:docstring xmlns=\"http://www.w3.org/1999/xhtml\" >\n"
"      Get a string indicating the type of UI role played by this object.\n"
"    </tp:docstring>\n"
"      <arg direction=\"out\" type=\"s\" >\n"
"        <tp:docstring>\n"
"      A UTF-8 string indicating the type of UI role played by this object.\n"
"    </tp:docstring>\n"
"      </arg>\n"
"    </method>\n"
"    <method name=\"getLocalizedRoleName\" >\n"
"      <tp:docstring xmlns=\"http://www.w3.org/1999/xhtml\" >\n"
"      Get a string indicating the type of UI role played by this object,\n"
"      translated to the current locale.\n"
"    </tp:docstring>\n"
"      <arg direction=\"out\" type=\"s\" >\n"
"        <tp:docstring>\n"
"      A UTF-8 string indicating the type of UI role played by this object.\n"
"    </tp:docstring>\n"
"      </arg>\n"
"    </method>\n"
"    <method name=\"getState\" >\n"
"      <tp:docstring>\n"
"      Get the current state of the object as a StateSet.\n"
"    </tp:docstring>\n"
"      <arg direction=\"out\" tp:type=\"StateSet\" type=\"au\" >\n"
"        <annotation value=\"QSpiStateSet\" name=\"com.trolltech.QtDBus.QtTypeName.Out0\" />\n"
"        <tp:docstring>\n"
"      A StateSet encapsulating the currently true states of the object.\n"
"      Returns an array of (currently two) 32-bit integers giving bitwise flags.\n"
"    </tp:docstring>\n"
"      </arg>\n"
"    </method>\n"
"    <method name=\"getAttributes\" >\n"
"      <tp:docstring xmlns=\"http://www.w3.org/1999/xhtml\" >\n"
"        <p>Get a list of properties applied to this object as a whole, as an \n"
"        AttributeSet consisting of name-value pairs. As such these attributes\n"
"        may be considered weakly-typed properties or annotations, as distinct\n"
"        from the strongly-typed interface instance data declared using the IDL \n"
"        \"attribute\" keyword.</p>\n"
"        <p>Not all objects have explicit \"name-value pair\" AttributeSet properties.      </p>\n"
"        <p>Attribute names and values may have any UTF-8 string value, however where possible,\n"
"        in order to facilitate consistent use and exposure of \"attribute\" properties by\n"
"        applications and AT clients, attribute names and values should chosen from  \n"
"        a publicly-specified namespace where appropriate.</p>\n"
"        <p>Where possible, the names and values in the name-value pairs\n"
"        should be chosen from well-established attribute namespaces\n"
"        using standard semantics.       \n"
"        For example, attributes of Accessible objects corresponding to XHTML content \n"
"        elements should correspond to attribute names and values specified in the w3c \n"
"        XHTML specification, at http://www.w3.org/TR/xhtml2, where such values are not \n"
"        already exposed via a more strongly-typed aspect of the AT-SPI API.\n"
"        Metadata names and\n"
"        values should be chosen from the 'Dublin Core' Metadata\n"
"        namespace using Dublin Core semantics:\n"
"        http://dublincore.org/dcregistry/\n"
"        Similarly, relevant structural metadata should be exposed\n"
"        using attribute names and values chosen from the CSS2 and WICD specification:\n"
"        http://www.w3.org/TR/1998/REC-CSS2-19980512\n"
"        WICD (http://www.w3.org/TR/2005/WD-WICD-20051121/).    </p>\n"
"        <p>Clients seeking semantic or typographical attributes associated with\n"
"        specific character spans of text content should use Text.getAttributeRun instead.\n"
"        The attributes returned by Accessible.getAttributes do not include\n"
"        \"text attributes\". (See Text.getAttributeRun)</p>\n"
"      </tp:docstring>\n"
"      <arg direction=\"out\" tp:type=\"AttributeSet\" type=\"as\" >\n"
"        <tp:docstring>\n"
"      An AttributeSet encapsulating any \"attribute values\" currently defined for the object.\n"
"    </tp:docstring>\n"
"      </arg>\n"
"    </method>\n"
"    <method name=\"getApplication\" >\n"
"      <tp:docstring xmlns=\"http://www.w3.org/1999/xhtml\" >\n"
"        <p>Get the containing Application for this object.</p>\n"
"      </tp:docstring>\n"
"      <arg direction=\"out\" tp:type=\"Application\" type=\"o\" >\n"
"        <tp:docstring>\n"
"      The Application instance to which this object belongs.\n"
"    </tp:docstring>\n"
"      </arg>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    QSpiAccessibleAdaptor(QObject *parent);
    virtual ~QSpiAccessibleAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QDBusObjectPath getApplication();
    QStringList getAttributes();
    QDBusObjectPath getChildAtIndex(int index);
    QList<QDBusObjectPath> getChildren();
    int getIndexInParent();
    QString getLocalizedRoleName();
    QSpiRelationArray getRelationSet();
    uint getRole();
    QString getRoleName();
    QSpiStateSet getState();
Q_SIGNALS: // SIGNALS
};

#endif
