/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -i adaptor_marshallers.h -c QSpiActionAdaptor -a action_adaptor org.freedesktop.atspi.Action.xml
 *
 * dbusxml2cpp is Copyright (C) 2008 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "action_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class QSpiActionAdaptor
 */

QSpiActionAdaptor::QSpiActionAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

QSpiActionAdaptor::~QSpiActionAdaptor()
{
    // destructor
}

int QSpiActionAdaptor::nActions() const
{
    // get the value of property nActions
    return qvariant_cast< int >(parent()->property("nActions"));
}

bool QSpiActionAdaptor::doAction(int index)
{
    // handle method call org.freedesktop.atspi.Action.doAction
    bool out0;
    QMetaObject::invokeMethod(parent(), "doAction", Q_RETURN_ARG(bool, out0), Q_ARG(int, index));
    return out0;
}

QSpiActionArray QSpiActionAdaptor::getActions()
{
    // handle method call org.freedesktop.atspi.Action.getActions
    QSpiActionArray index;
    QMetaObject::invokeMethod(parent(), "getActions", Q_RETURN_ARG(QSpiActionArray, index));
    return index;
}

QString QSpiActionAdaptor::getDescription(int index)
{
    // handle method call org.freedesktop.atspi.Action.getDescription
    QString out0;
    QMetaObject::invokeMethod(parent(), "getDescription", Q_RETURN_ARG(QString, out0), Q_ARG(int, index));
    return out0;
}

QString QSpiActionAdaptor::getKeyBinding(int index)
{
    // handle method call org.freedesktop.atspi.Action.getKeyBinding
    QString out0;
    QMetaObject::invokeMethod(parent(), "getKeyBinding", Q_RETURN_ARG(QString, out0), Q_ARG(int, index));
    return out0;
}

QString QSpiActionAdaptor::getName(int index)
{
    // handle method call org.freedesktop.atspi.Action.getName
    QString out0;
    QMetaObject::invokeMethod(parent(), "getName", Q_RETURN_ARG(QString, out0), Q_ARG(int, index));
    return out0;
}

