/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp org.freedesktop.atspi.DeviceEventController.xml -i proxy_marshallers.h -c QSpiDECProxy -p device_event_controller_proxy
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "device_event_controller_proxy.h"

/*
 * Implementation of interface class QSpiDECProxy
 */

QSpiDECProxy::QSpiDECProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

QSpiDECProxy::~QSpiDECProxy()
{
}

