/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -i adaptor_marshallers.h -c QSpiEditableTextAdaptor -a editable_text_adaptor org.freedesktop.atspi.EditableText.xml
 *
 * dbusxml2cpp is Copyright (C) 2008 Nokia Corporation and/or its subsidiary(-ies).
 *
 */

#include "editable_text_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

#include <QAccessibleTextInterface>
#include <QAccessibleEditableTextInterface>

/*
 * Implementation of adaptor class QSpiEditableTextAdaptor
 */

#define EDITABLE_TEXT_INTERFACE static_cast <QSpiAccessibleObject *>(parent())->getInterface().editableTextInterface()
#define TEXT_INTERFACE static_cast <QSpiAccessibleObject *>(parent())->getInterface().textInterface()

QSpiEditableTextAdaptor::QSpiEditableTextAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

QSpiEditableTextAdaptor::~QSpiEditableTextAdaptor()
{
    // destructor
}

void QSpiEditableTextAdaptor::copyText(int startPos, int endPos)
{
    return EDITABLE_TEXT_INTERFACE->copyText (startPos, endPos);
}

bool QSpiEditableTextAdaptor::cutText(int startPos, int endPos)
{
    EDITABLE_TEXT_INTERFACE->cutText (startPos, endPos);
    return TRUE;
}

bool QSpiEditableTextAdaptor::deleteText(int startPos, int endPos)
{
    EDITABLE_TEXT_INTERFACE->deleteText (startPos, endPos);
    return TRUE;
}

bool QSpiEditableTextAdaptor::insertText(int position, const QString &text, int length)
{
    QString resized (text);
    resized.resize(length);
    EDITABLE_TEXT_INTERFACE->insertText (position, text);
    return TRUE;
}

bool QSpiEditableTextAdaptor::pasteText(int position)
{
    EDITABLE_TEXT_INTERFACE->pasteText (position);
    return TRUE;
}

bool QSpiEditableTextAdaptor::setTextContents(const QString &newContents)
{
    EDITABLE_TEXT_INTERFACE->replaceText (0, TEXT_INTERFACE->characterCount(), newContents);
    return TRUE;
}
