/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp org.freedesktop.atspi.Registry.xml -i marshallers.h -c QSpiRegistryProxy -p registry-proxy
 *
 * dbusxml2cpp is Copyright (C) 2008 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "registry_proxy.h"

/*
 * Implementation of interface class QSpiRegistryProxy
 */

QSpiRegistryProxy::QSpiRegistryProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

QSpiRegistryProxy::~QSpiRegistryProxy()
{
}

