/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -i adaptor_marshallers.h -c QSpiTableAdaptor -a table_adaptor org.freedesktop.atspi.Table.xml
 *
 * dbusxml2cpp is Copyright (C) 2008 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef TABLE_ADAPTOR_H_1239786808
#define TABLE_ADAPTOR_H_1239786808

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "adaptor_marshallers.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.freedesktop.atspi.Table
 */
class QSpiTableAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.atspi.Table")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.atspi.Table\" >\n"
"    <property access=\"read\" type=\"i\" name=\"nRows\" />\n"
"    <property access=\"read\" type=\"i\" name=\"nColumns\" />\n"
"    <property access=\"read\" type=\"o\" name=\"caption\" />\n"
"    <property access=\"read\" type=\"o\" name=\"summary\" />\n"
"    <property access=\"read\" type=\"i\" name=\"nSelectedRows\" />\n"
"    <property access=\"read\" type=\"i\" name=\"nSelectedColumns\" />\n"
"    <method name=\"getAccessibleAt\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"row\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"column\" />\n"
"      <arg direction=\"out\" type=\"o\" />\n"
"    </method>\n"
"    <method name=\"getIndexAt\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"row\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"column\" />\n"
"      <arg direction=\"out\" type=\"i\" />\n"
"    </method>\n"
"    <method name=\"getRowAtIndex\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"index\" />\n"
"      <arg direction=\"out\" type=\"i\" />\n"
"    </method>\n"
"    <method name=\"getColumnAtIndex\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"index\" />\n"
"      <arg direction=\"out\" type=\"i\" />\n"
"    </method>\n"
"    <method name=\"getRowDescription\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"row\" />\n"
"      <arg direction=\"out\" type=\"s\" />\n"
"    </method>\n"
"    <method name=\"getColumnDescription\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"column\" />\n"
"      <arg direction=\"out\" type=\"s\" />\n"
"    </method>\n"
"    <method name=\"getRowExtentAt\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"row\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"column\" />\n"
"      <arg direction=\"out\" type=\"i\" />\n"
"    </method>\n"
"    <method name=\"getColumnExtentAt\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"row\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"column\" />\n"
"      <arg direction=\"out\" type=\"i\" />\n"
"    </method>\n"
"    <method name=\"getRowHeader\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"row\" />\n"
"      <arg direction=\"out\" type=\"o\" />\n"
"    </method>\n"
"    <method name=\"getColumnHeader\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"column\" />\n"
"      <arg direction=\"out\" type=\"o\" />\n"
"    </method>\n"
"    <method name=\"getSelectedRows\" >\n"
"      <arg direction=\"out\" type=\"ai\" />\n"
"      <annotation value=\"QSpiSelectedRowList\" name=\"com.trolltech.QtDBus.QtTypeName.Out0\" />\n"
"    </method>\n"
"    <method name=\"getSelectedColumns\" >\n"
"      <arg direction=\"out\" type=\"ai\" />\n"
"      <annotation value=\"QSpiSelectedColumnList\" name=\"com.trolltech.QtDBus.QtTypeName.Out0\" />\n"
"    </method>\n"
"    <method name=\"isRowSelected\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"row\" />\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"isColumnSelected\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"column\" />\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"isSelected\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"row\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"column\" />\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"addRowSelection\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"row\" />\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"addColumnSelection\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"column\" />\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"removeRowSelection\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"row\" />\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"removeColumnSelection\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"column\" />\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"getRowColumnExtentsAtIndex\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"index\" />\n"
"      <arg direction=\"out\" type=\"i\" name=\"row\" />\n"
"      <arg direction=\"out\" type=\"i\" name=\"col\" />\n"
"      <arg direction=\"out\" type=\"i\" name=\"row_extents\" />\n"
"      <arg direction=\"out\" type=\"i\" name=\"col_extents\" />\n"
"      <arg direction=\"out\" type=\"b\" name=\"is_selected\" />\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    QSpiTableAdaptor(QObject *parent);
    virtual ~QSpiTableAdaptor();

public: // PROPERTIES
    Q_PROPERTY(QDBusObjectPath caption READ caption)
    QDBusObjectPath caption() const;

    Q_PROPERTY(int nColumns READ nColumns)
    int nColumns() const;

    Q_PROPERTY(int nRows READ nRows)
    int nRows() const;

    Q_PROPERTY(int nSelectedColumns READ nSelectedColumns)
    int nSelectedColumns() const;

    Q_PROPERTY(int nSelectedRows READ nSelectedRows)
    int nSelectedRows() const;

    Q_PROPERTY(QDBusObjectPath summary READ summary)
    QDBusObjectPath summary() const;

public Q_SLOTS: // METHODS
    bool addColumnSelection(int column);
    bool addRowSelection(int row);
    QDBusObjectPath getAccessibleAt(int row, int column);
    int getColumnAtIndex(int index);
    QString getColumnDescription(int column);
    int getColumnExtentAt(int row, int column);
    QDBusObjectPath getColumnHeader(int column);
    int getIndexAt(int row, int column);
    int getRowAtIndex(int index);
    int getRowColumnExtentsAtIndex(int index, int &col, int &row_extents, int &col_extents, bool &is_selected, bool &out5);
    QString getRowDescription(int row);
    int getRowExtentAt(int row, int column);
    QDBusObjectPath getRowHeader(int row);
    QSpiIntList getSelectedColumns();
    QSpiIntList getSelectedRows();
    bool isColumnSelected(int column);
    bool isRowSelected(int row);
    bool isSelected(int row, int column);
    bool removeColumnSelection(int column);
    bool removeRowSelection(int row);
Q_SIGNALS: // SIGNALS
};

#endif
