/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -i adaptor_marshallers.h -c QSpiTableAdaptor -a table_adaptor org.freedesktop.atspi.Table.xml
 *
 * dbusxml2cpp is Copyright (C) 2008 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */


#include "table_adaptor.h"
#include "object.h"
#include "cache.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

#include <QAccessibleTableInterface>

/*
 * Implementation of adaptor class QSpiTableAdaptor
 */

#define TABLE_INTERFACE      static_cast <QSpiAccessibleObject *>(parent())->getInterface().tableInterface()
#define ACCESSIBLE_INTERFACE static_cast <QSpiAccessibleObject *>(parent())->getInterface()
#define ACCESSIBLE_CACHE     static_cast <QSpiAccessibleObject *>(parent())->cache

#define MAX_SELECTED_COLUMNS 1000
#define MAX_SELECTED_ROWS    1000

QSpiTableAdaptor::QSpiTableAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

QSpiTableAdaptor::~QSpiTableAdaptor()
{
    // destructor
}

QDBusObjectPath QSpiTableAdaptor::caption() const
{
    return ACCESSIBLE_CACHE->lookupObject (TABLE_INTERFACE->caption()->object())->getPath();
}

int QSpiTableAdaptor::nColumns() const
{
    return TABLE_INTERFACE->columnCount ();
}

int QSpiTableAdaptor::nRows() const
{
    return TABLE_INTERFACE->rowCount ();
}

int QSpiTableAdaptor::nSelectedColumns() const
{
    return TABLE_INTERFACE->selectedColumnCount ();
}

int QSpiTableAdaptor::nSelectedRows() const
{
    return TABLE_INTERFACE->selectedRowCount ();
}

QDBusObjectPath QSpiTableAdaptor::summary() const
{
    return ACCESSIBLE_CACHE->lookupObject (TABLE_INTERFACE->summary()->object())->getPath();
}

bool QSpiTableAdaptor::addColumnSelection(int column)
{
    TABLE_INTERFACE->selectColumn (column);
    return TRUE;
}

bool QSpiTableAdaptor::addRowSelection(int row)
{
    TABLE_INTERFACE->selectRow (row);
    return TRUE;
}

QDBusObjectPath QSpiTableAdaptor::getAccessibleAt(int row, int column)
{
    return ACCESSIBLE_CACHE->lookupObject (TABLE_INTERFACE->accessibleAt(row, column)->object())->getPath();
}

int QSpiTableAdaptor::getColumnAtIndex(int index)
{
    return TABLE_INTERFACE->columnIndex (index);
}

QString QSpiTableAdaptor::getColumnDescription(int column)
{
    return TABLE_INTERFACE->columnDescription (column);
}

int QSpiTableAdaptor::getColumnExtentAt(int row, int column)
{
    return TABLE_INTERFACE->columnSpan (row, column);
}

QDBusObjectPath QSpiTableAdaptor::getColumnHeader(int column)
{
    // TODO There should be a column param in this function right?
    return ACCESSIBLE_CACHE->lookupObject (TABLE_INTERFACE->columnHeader()->object())->getPath();
}

int QSpiTableAdaptor::getIndexAt(int row, int column)
{
    return TABLE_INTERFACE->childIndex (row, column);
}

int QSpiTableAdaptor::getRowAtIndex(int index)
{
    int row, column, rowSpan, columnSpan;
    bool isSelected;

    TABLE_INTERFACE->cellAtIndex (index, &row, &column, &rowSpan, &columnSpan, &isSelected);
    return row;
}

int QSpiTableAdaptor::getRowColumnExtentsAtIndex(int index,
                                                 int &col,
                                                 int &row_extents,
                                                 int &col_extents,
                                                 bool &is_selected,
                                                 bool &out5)
{
    int row, column, rowSpan, columnSpan;
    bool isSelected;

    TABLE_INTERFACE->cellAtIndex (index, &row, &column, &rowSpan, &columnSpan, &isSelected);
    col = column;
    row_extents = rowSpan;
    col_extents = columnSpan;
    is_selected = isSelected;
    if (index < ACCESSIBLE_INTERFACE.childCount())
        out5 = TRUE;
    else
        out5 = FALSE;
    return row;
}

QString QSpiTableAdaptor::getRowDescription(int row)
{
    return TABLE_INTERFACE->rowDescription (row);
}

int QSpiTableAdaptor::getRowExtentAt(int row, int column)
{
    return TABLE_INTERFACE->rowSpan (row, column);
}

QDBusObjectPath QSpiTableAdaptor::getRowHeader(int row)
{
    // TODO There should be a row param here right?
    return ACCESSIBLE_CACHE->lookupObject (TABLE_INTERFACE->rowHeader()->object())->getPath();
}

QSpiIntList QSpiTableAdaptor::getSelectedColumns()
{
    QSpiIntList columns;
    TABLE_INTERFACE->selectedColumns (MAX_SELECTED_COLUMNS, &columns);
    return columns;
}

QSpiIntList QSpiTableAdaptor::getSelectedRows()
{
    QSpiIntList rows;
    TABLE_INTERFACE->selectedRows (MAX_SELECTED_ROWS, &rows);
    return rows;
}

bool QSpiTableAdaptor::isColumnSelected(int column)
{
    return TABLE_INTERFACE->isColumnSelected (column);
}

bool QSpiTableAdaptor::isRowSelected(int row)
{
    return TABLE_INTERFACE->isRowSelected (row);
}

bool QSpiTableAdaptor::isSelected(int row, int column)
{
    return TABLE_INTERFACE->isSelected (row, column);
}

bool QSpiTableAdaptor::removeColumnSelection(int column)
{
    TABLE_INTERFACE->unselectColumn (column);
    return TRUE;
}

bool QSpiTableAdaptor::removeRowSelection(int row)
{
    TABLE_INTERFACE->unselectRow (row);
    return TRUE;
}
