/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -i adaptor_marshallers.h -c QSpiTreeAdaptor -a tree_adaptor org.freedesktop.atspi.Tree.xml
 *
 * dbusxml2cpp is Copyright (C) 2008 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef TREE_ADAPTOR_H_1239786097
#define TREE_ADAPTOR_H_1239786097

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "adaptor_marshallers.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.freedesktop.atspi.Tree
 */
class QSpiTreeAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.atspi.Tree")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.atspi.Tree\" >\n"
"    <method name=\"getRoot\" >\n"
"      <arg direction=\"out\" type=\"o\" name=\"root\" />\n"
"    </method>\n"
"    <method name=\"getTree\" >\n"
"      <arg direction=\"out\" type=\"a(ooaoassusau)\" name=\"nodes\" />\n"
"      <annotation value=\"QSpiAccessibleCacheArray\" name=\"com.trolltech.QtDBus.QtTypeName.Out0\" />\n"
"    </method>\n"
"    <signal name=\"updateAccessible\" >\n"
"      <arg type=\"a(ooaoassusau)\" name=\"nodesAdded\" />\n"
"      <annotation value=\"QSpiAccessibleCacheArray\" name=\"com.trolltech.QtDBus.QtTypeName.In0\" />\n"
"    </signal>\n"
"    <signal name=\"removeAccessible\" >\n"
"      <arg type=\"o\" name=\"nodeRemoved\" />\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    QSpiTreeAdaptor(QObject *parent);
    virtual ~QSpiTreeAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QDBusObjectPath getRoot();
    QSpiAccessibleCacheArray getTree();
Q_SIGNALS: // SIGNALS
    void removeAccessible(const QDBusObjectPath &nodeRemoved);
    void updateAccessible(const QSpiAccessibleCacheArray &nodesAdded);
};

#endif
