/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -i adaptor_marshallers.h -c QSpiTreeAdaptor -a tree-adaptor org.freedesktop.atspi.Tree.xml
 *
 * dbusxml2cpp is Copyright (C) 2008 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef TREE-ADAPTOR_H_1238937785
#define TREE-ADAPTOR_H_1238937785

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "adaptor_marshallers.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.freedesktop.atspi.Tree
 */
class QSpiTreeAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.atspi.Tree")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.atspi.Tree\" >\n"
"    <tp:docstring xmlns=\"http://www.w3.org/1999/xhtml\" >\n"
"      <p>The Tree interface provides access to all\n"
"			of the Accessible objects that an application\n"
"			has available. Information about the objects is \n"
"			transferred as a collection to reduce IPC usage.</p>\n"
"    </tp:docstring>\n"
"    <method name=\"getRoot\" >\n"
"      <tp:docstring xmlns=\"http://www.w3.org/1999/xhtml\" >\n"
"        <p>Gets the D-Bus object path of the \n"
"				root accessible object of the application.</p>\n"
"      </tp:docstring>\n"
"      <arg direction=\"out\" type=\"o\" name=\"root\" >\n"
"        <tp:docstring xmlns=\"http://www.w3.org/1999/xhtml\" >\n"
"          <p>Path of root Accessible object.</p>\n"
"        </tp:docstring>\n"
"      </arg>\n"
"    </method>\n"
"    <method name=\"getTree\" >\n"
"      <tp:docstring xmlns=\"http://www.w3.org/1999/xhtml\" >\n"
"        <p>Transfers structures representing ALL\n"
"				Accessible objects that currently exist in the\n"
"				application. This should be used to create\n"
"				a mirror of the tree of Accessibles within the AT.</p>\n"
"      </tp:docstring>\n"
"      <arg direction=\"out\" tp:type=\"AccessibleProxy[]\" type=\"a(ooaoassusau)\" name=\"nodes\" >\n"
"        <annotation value=\"QSpiAccessibleCacheArray\" name=\"com.trolltech.QtDBus.QtTypeName.Out0\" />\n"
"        <tp:docstring xmlns=\"http://www.w3.org/1999/xhtml\" >\n"
"          <p>Array of Accessible Object proxy structures.</p>\n"
"        </tp:docstring>\n"
"      </arg>\n"
"    </method>\n"
"    <signal name=\"updateAccessible\" >\n"
"      <tp:docstring xmlns=\"http://www.w3.org/1999/xhtml\" >\n"
"        <p>Updates all mirrors. Re-sends all all the \n"
"				accessible objects that have changed since the last\n"
"				updateTree signal was send</p>\n"
"      </tp:docstring>\n"
"      <arg tp:type=\"AccessibleProxy[]\" type=\"a(ooaoassusau)\" name=\"nodesAdded\" >\n"
"        <annotation value=\"QSpiAccessibleCacheArray\" name=\"com.trolltech.QtDBus.QtTypeName.In0\" />\n"
"        <tp:docstring xmlns=\"http://www.w3.org/1999/xhtml\" >\n"
"          <p>Array of Accessible Object proxy structures to be added.</p>\n"
"        </tp:docstring>\n"
"      </arg>\n"
"    </signal>\n"
"    <signal name=\"removeAccessible\" >\n"
"      <arg type=\"o\" name=\"nodeRemoved\" >\n"
"        <tp:docstring xmlns=\"http://www.w3.org/1999/xhtml\" >\n"
"          <p>Accessible Object proxy structure to be removed.</p>\n"
"        </tp:docstring>\n"
"      </arg>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    QSpiTreeAdaptor(QObject *parent);
    virtual ~QSpiTreeAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QDBusObjectPath getRoot();
    QSpiAccessibleCacheArray getTree();
Q_SIGNALS: // SIGNALS
    void removeAccessible(const QDBusObjectPath &nodeRemoved);
    void updateAccessible(const QSpiAccessibleCacheArray &nodesAdded);
};

#endif
