/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -i adaptor_marshallers.h -c QSpiTreeAdaptor -a tree_adaptor org.freedesktop.atspi.Tree.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef TREE_ADAPTOR_H_1259750988
#define TREE_ADAPTOR_H_1259750988

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "adaptor_marshallers.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.freedesktop.atspi.Tree
 */
class QSpiTreeAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.atspi.Tree")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.atspi.Tree\" >\n"
"    <method name=\"GetRoot\" >\n"
"      <arg direction=\"out\" type=\"o\" name=\"root\" />\n"
"    </method>\n"
"    <method name=\"GetTree\" >\n"
"      <arg direction=\"out\" type=\"a(o(so)a(so)assusau)\" name=\"nodes\" />\n"
"      <annotation value=\"QSpiAccessibleCacheArray\" name=\"com.trolltech.QtDBus.QtTypeName.Out0\" />\n"
"    </method>\n"
"    <signal name=\"UpdateAccessible\" >\n"
"      <arg type=\"((so)(so)a(so)assusau)\" name=\"nodesAdded\" />\n"
"      <annotation value=\"QSpiAccessibleCacheArray\" name=\"com.trolltech.QtDBus.QtTypeName.In0\" />\n"
"    </signal>\n"
"    <signal name=\"RemoveAccessible\" >\n"
"      <arg type=\"o\" name=\"nodeRemoved\" />\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    QSpiTreeAdaptor(QObject *parent);
    virtual ~QSpiTreeAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QDBusObjectPath GetRoot();
    QSpiAccessibleCacheArray GetTree();
Q_SIGNALS: // SIGNALS
    void RemoveAccessible(const QDBusObjectPath &nodeRemoved);
    void UpdateAccessible(const QSpiAccessibleCacheArray &nodesAdded);
};

#endif
