/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -i adaptor_marshallers.h -c QSpiValueAdaptor -a value_adaptor org.freedesktop.atspi.Value.xml
 *
 * dbusxml2cpp is Copyright (C) 2008 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef VALUE_ADAPTOR_H_1239786880
#define VALUE_ADAPTOR_H_1239786880

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "adaptor_marshallers.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.freedesktop.atspi.Value
 */
class QSpiValueAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.atspi.Value")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.atspi.Value\" >\n"
"    <property access=\"read\" type=\"d\" name=\"minimumValue\" />\n"
"    <property access=\"read\" type=\"d\" name=\"maximumValue\" />\n"
"    <property access=\"read\" type=\"d\" name=\"minimumIncrement\" />\n"
"    <property access=\"readwrite\" type=\"d\" name=\"currentValue\" />\n"
"  </interface>\n"
        "")
public:
    QSpiValueAdaptor(QObject *parent);
    virtual ~QSpiValueAdaptor();

public: // PROPERTIES
    Q_PROPERTY(double currentValue READ currentValue WRITE setCurrentValue)
    double currentValue() const;
    void setCurrentValue(double value);

    Q_PROPERTY(double maximumValue READ maximumValue)
    double maximumValue() const;

    Q_PROPERTY(double minimumIncrement READ minimumIncrement)
    double minimumIncrement() const;

    Q_PROPERTY(double minimumValue READ minimumValue)
    double minimumValue() const;

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
};

#endif
